[versions]

agp = "8.13.1"
kotlin = "2.2.21"
kotlinxCoroutines = "1.10.2"
coreKtx = "1.17.0"
junit = "4.13.2"
lifecycle = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.11.00"
streamLog = "1.3.4"
streamChatAndroid = "6.27.0"
retrofit = "2.11.0"
okhttp = "4.12.0"
moshi = "1.15.1"

[libraries]
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
stream-log = { group = "io.getstream", name = "stream-log", version.ref = "streamLog" }
stream-chat-android-client = { group = "io.getstream", name = "stream-chat-android-client", version.ref = "streamChatAndroid" }
stream-chat-android-state = { group = "io.getstream", name = "stream-chat-android-state", version.ref = "streamChatAndroid" }
stream-chat-android-offline = { group = "io.getstream", name = "stream-chat-android-offline", version.ref = "streamChatAndroid" }
stream-chat-android-compose = { group = "io.getstream", name = "stream-chat-android-compose", version.ref = "streamChatAndroid" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[bundles]
stream-chat = [
    "stream-log",
    "stream-chat-android-client",
    "stream-chat-android-state",
    "stream-chat-android-offline",
    "stream-chat-android-compose"
]
retrofit = [
    "retrofit",
    "retrofit-converter-moshi",
    "okhttp",
    "okhttp-logging-interceptor",
    "moshi",
    "moshi-kotlin",
]
androidx-compose = [
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-material3",
]
